[package]
name = "minigolf"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.14.2", features = ["mp3"]}
bevy_mod_raycast = "0.18.0"
bevy_editor_pls = "0.9"
bevy_render = "0.14.2"
bevy_renet = "0.0.12"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
